### ISSUE TITLE
Can't whisper "0"

### ISSUE THREAD

**Issue by JJAYL** [destinygg/chat#31]
if you type "/w CeneZa 0" or type "0" into the one on one whisper chat you get the following error:
"Required field missing message"

**Comment by tbrown1979** [comment]
@cene-co-za This issue is actually with the destinygg/website, I think. `empty` in `php` will return `true` if the value is `"0"`, which seems to be what is happening here when this service `POST`s to the website. [This](https://github.com/destinygg/website/blob/master/lib/Destiny/Common/Utils/FilterParams.php#L57) is returning `true` and thus preventing users from private messaging `"0"`.
